name: Build and test lab-cicd

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    name: Build cicd-lab
    env:
      GITHUB_USER: nissebergman
      IMAGE_REGISTRY: ghcr.io/nissebergman
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.IMAGE_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set environment variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ env.IMAGE_REGISTRY }}/ci-cd-test:${{ env.SHA_SHORT }},${{ env.IMAGE_REGISTRY }}/ci-cd-test:dev"